_target_: bioaed.models.inceptiontime.InceptionTime
num_classes: ${dataset.num_classes}
in_channels: ${dataset.n_mels}
depth: 6
n_filters: 32
kernel_size: 41  # produces branches [40, 20, 10]
use_bottleneck: true
bottleneck_size: 32
use_residual: true
