name: anuraset
root_dir: ${oc.env:DATA_DIR,data}/anuraset
sample_rate: 22050
segment_duration: 3.0
n_mels: 64
hop_length: 220 # ~10ms @ 22050Hz
win_length: 550 # ~25ms @ 22050Hz
num_classes: 42
time_frames: 301  # floor(sample_rate * segment_duration / hop_length) + 1
batch_size: 64
num_workers: 8
pin_memory: true
normalize: true
