name: aswine
root_dir: ${oc.env:DATA_DIR,data}/aswine
meta_variant: 1s_pruned # raw | 1s | 1s_pruned
sample_rate: 16000
segment_duration: 1.0
n_mels: 64
hop_length: 160 # 10ms @ 16kHz
win_length: 400 # 25ms @ 16kHz
num_classes: 7
time_frames: 101  # floor(sample_rate * segment_duration / hop_length) + 1
batch_size: 64
num_workers: 8
pin_memory: true
normalize: true
